apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: prod

resources:
  - namespace.yaml
  - ../../base
patches:  
- path: configmap-patch.yaml
- path: ingress-patch.yaml
- path: patch-deployment.yaml
- path: secret-patch.yaml
