apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
data:
  APP_NAME: "k8s-argocd-demo"
  ENVIRONMENT: "base"
  WELCOME_MESSAGE: "Hello from base!"
  LOG_LEVEL: "INFO"
  FAIL_RATE: "0.0"
